language: generic
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
- docker build -t docker-react -f Dockerfile.dev .
script:
- docker run  -e  CI=true docker-react npm run test

deploy:
  provider: gae
  keyfile: ...
  project: docker-react`  
